server:
  port: 18002
  servlet:
    # 应用的访问路径
    context-path: /
spring:
  application:
    name: mango-admin-web
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
# 项目相关配置
pomelo:
  # 名称
  name: RuoYi
  # 版本
  version: 4.1.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: E:/pomelo/uploadPath
  # 获取ip地址开关
  addressEnabled: true