server:
  port: 18002
  servlet:
    # 应用的访问路径
    context-path: /
spring:
  application:
    name: mango-admin-web
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

